### ISSUE TITLE
Allow names to be used in deps CLI

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#100]
Once gh-99 is complete, we can update the CLI to support querying for names. This can be done by moving the organization and module parsing to the client-side and then sending the appropriate request. This should simplify the developer experience and provide a nice stepping stone to v1beta.

**Comment by mjpitz** [comment]
Right now, v1alpha's modules are keyed by the `language`, `organization`, and `module`. More or less a synthetic representation of `name`. As a result, you need to pass in all three when performing a query. This requires people to understand the deps.cloud parsing scheme (not a super great UX). The idea in `v1beta` is to move toward the canonical `name` allowing node folks to query using their scheme (`@depscloud/api`) while allowing the Java folks to query using theirs (`cloud.deps:api`). This drastically reduces the cognitive load on our end users.

The idea here is to fake it. Let users pass in the name, but then parse it out into the `organization` / `module` and setting them appropriately before making the request. I would start by looking at uses of these methods:

https://github.com/depscloud/depscloud/blob/main/deps/internal/cmds/get/common.go#L10-L16
https://github.com/depscloud/depscloud/blob/main/deps/internal/cmds/get/common.go#L24-L30

If further [API](https://github.com/depscloud/api) changes are needed, I'd hold off on them and find a way to work within the confines of the client for now. I'm hoping to make the move to `v1beta` faster than that while deployments are [presumably] low.

References:
* [v1alpha data model](https://deps.cloud/docs/concepts/data-model/)
* [source code for the command line tool](https://github.com/depscloud/depscloud/tree/main/deps)

**Comment by shinnlok** [comment]
Thanks for the explanation. You can assign to me and I'll give it a shot.
