### ISSUE TITLE
Support indexing Python

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#18]
Let's figure out the right way to index python projects. Right now, most python projects are deployed using `setup.py` files. This is rough because it means we need to parse python code to be able to extract dependencies. Some projects have `requirements.txt` but that only lists dependencies, not the core module itself.

`Pipfile` looks really promising as it provides a way to manage dependencies in a declarative way but it's unclear what scale this mechanism is used: https://github.com/pypa/pipfile

**Comment by chargao** [comment]
plz assign 2 me

**Comment by mjpitz** [comment]
@chargao I'm going to sit down and take a crack at this if you don't mind. Let me know if you have something started. I might be able to work with what you have.

**Comment by chargao** [comment]
Oh shoot, I'm so sorry, this slipped off of my radar. :(

**Comment by mjpitz** [comment]
@chargao no worries! thanks for digging into it!
