### ISSUE TITLE
deps is not built for Darwin/arm64

### ISSUE THREAD

**Issue by csalch-indeed** [depscloud/depscloud#245]
Presently the deps cli client is not installable on Apple Silicon based machines. It looks like all that is needed is the removal of an ignore in the goreleaser config.

**Comment by mjpitz** [comment]
Its a bit more than that. We need to upgrade go versions I believe...

https://blog.golang.org/ports

**Comment by csalch-indeed** [comment]
You may be right on that .. I inadvertently built with 1.16 locally while testing .. hmm

**Comment by mjpitz** [comment]
Feel free to test it out. It definitely needs go 1.16 and I just updated locally, but have been hesitant to update after the fun things in 1.15. From an acceptance test perspective, things seemed to work fine, just not quite ready yet. Feel free to start a 1.16 branch that we can start tracking and add the apple silicon args for the `deps` cli.

**Comment by csalch-indeed** [comment]
Let me git this a shot ...

**Comment by csalch-indeed** [comment]
> I noticed that it doesn't appear to build the deps cli tool in a docker container. 

Never mind, I see the build for it. I was just confused by the other deps targets..
