### ISSUE TITLE
Add troubleshooting command

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#3]
To troubleshoot issues, it would be useful to add a troubleshooting target that is able to output useful debugging information.

Some good information to output:
- protocol (env.DEPSCLOUD_PROTOCOL || grpc)
- base url (env.DEPSCLOUD_BASE_URL || https://api.deps.cloud)
- os
- arch

**Comment by mjpitz** [comment]
Now that we have `/healthz`, we can also report on the health of the upstream systems and capabilities as part of this.

**Comment by mjpitz** [comment]
Opened gh-58 to add a `/versionz` endpoint that can be used to report server side version information.

**Comment by jakeryang** [comment]
I'm interested in contributing to this issue.

Does it just involve the file `depscloud/extractor/src/main.ts` and add something like a `/troubelshoot` endpoint?

**Comment by mjpitz** [comment]
@jakeryang , I think @pavan-kalyan was going to take a look at this. @pavan-kalyan , correct me if I'm wrong.

**Comment by pavan-kalyan** [comment]
I was going to look at it, but I think @jakeryang was quicker so, he can take a shot at if he wants.

**Comment by jakeryang** [comment]
@pavan-kalyan I was checking out #88 and you seem to know exactly what to do so it would be better for you to implement this.

**Comment by pavan-kalyan** [comment]
Thanks!
Just to clarify this is a cli command rather than an endpoint right?
E.g `tracker troubleshoot`, would output all the information (by hitting the healthz and version endpoints if necessary)

**Comment by pavan-kalyan** [comment]
@jakeryang  if you want you can take a look at 
https://github.com/depscloud/depscloud/issues/69

**Comment by jakeryang** [comment]
> 
> 
> @jakeryang if you want you can take a look at
> #69

Thanks, will do.

**Comment by mjpitz** [comment]
@pavan-kalyan this would be a single troubleshoot command on the `deps` CLI tool. This tool hits the gateway process as demonstrated here: https://deps.cloud/docs/concepts/architecture/). The troubleshoot command would query the gateway for health and version information to start. Eventually, we could look at pulling the metrics endpoint and interpreting some of that information. For now, let's output the version information (client and server), the information listed in the first comment, and the status of the gateway service (accessed via the baseURLl) and its checks.

**Comment by pavan-kalyan** [comment]
Ok, thanks. I'll get started on this!
