### ISSUE TITLE
Add `/version` endpoint

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#58]
This endpoint should output some server side version information about the system. The data should be output in JSON. This information can be used to determine API compatibility with the CLI and other interfaces.

**Comment by pavan-kalyan** [comment]
Do you have a specific set of information that would need to be displayed other than a version number?

I see some info in [gateway](https://github.com/depscloud/depscloud/blob/main/gateway/main.go), should some of these be displayed?

**Comment by mjpitz** [comment]
Hey there! I just put up a more centralized server handler that can be used to pass to make some of this easier:

**Comment by mjpitz** [comment]
On the NodeJS side of the world, we could set an arbitrary JSON block in `package.json` and read it from `main.js`. It would require some CI work, but nothing too complicated. Definitely willing to help on the Node side if needed.

**Comment by mjpitz** [comment]
I've updated the nodejs release process to add a `meta` object to the package.json file. Rendering an endpoint for NodeJS should be as easy as reading that file and writing out the meta block in json.

**Comment by pavan-kalyan** [comment]
Hi, thanks a lot for clarifying and making things easier. I'll get started on this right away!

**Comment by pavan-kalyan** [comment]
From what I understand from the Makefile. During the build (specfically install command) of each golang service, the variables are set (if the service has those variables).
gateway and tracker both use /internal/mux, so for them I have set variables version, commit, date. which are set by the goreleaser tool and used a Version struct to pass this info to internal/mux as part of the Config. but indexer and deps currently do not use /internal/mux. So no changes are required to deps and indexer?

**Comment by mjpitz** [comment]
Correct. Although, all of them should have a version subcommand for printing information (kinda like how deps works)
