### ISSUE TITLE
GoModExtractor should support a retract tag

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#69]
With the release of Go 1.16 on the horizon, we should add support for the `retract` tag in a `go.mod` file. This acts as an explicit exclusion.

https://tip.golang.org/doc/go1.16#go-command

**Comment by pavan-kalyan** [comment]
Is there currently a specific version of depscloud that would need to be currently retracted/excluded?

**Comment by mjpitz** [comment]
What do you mean?

**Comment by pavan-kalyan** [comment]
My bad, I misunderstood the issue.
So the task is to add the case for 'retract' [here](https://github.com/depscloud/depscloud/blob/main/extractor/src/extractors/GoModExtractor.ts#L88-L93) ?

**Comment by mjpitz** [comment]
Correct. Right now we don't "handle" exclusions per-se but we do include them in the graph with the associated scope.

**Comment by mjpitz** [comment]
@jakeryang I think there might be some more work here. Looks like retract is used to retract a specific version of the current module, rather than dependency. We still need to handle the symbol, but I don't think we want to do anything with the information yet. There's some future work underway that would be able to handle this information a bit nicer.

**Comment by mjpitz** [comment]
@mkw have you thought about how we might incorporate blocklist / retractions into the depscloud data model? I haven't spent much time on it, but it seems like an easy thing to add as an array attribute to the module.

**Comment by mkw** [comment]
I just assumed it would become a "label." Provided we can search/filter on them, that should be sufficient.

**Comment by mjpitz** [comment]
A downside to the labels is that they're just string values, so you need to either put each as their own key or join them in a single value.

**Comment by mkw** [comment]
I assumed something like `"rejected": "true"`? Of course, it would be even better if there was some sort of `status` on each item with more built-in handling, but I don't know of any "standard" way to encode rejected library versions.

**Comment by mjpitz** [comment]
hmmm.. I'll have to think on this some more.

Either way, the current parsing scheme for go.mod is a bit fragile to changes. I think a better solution would be to update the code on the server to have the default block be more graceful: https://github.com/depscloud/depscloud/blob/0dfd21eae6559985a70e2b86f559eb0ba464fe79/extractor/src/extractors/GoModExtractor.ts#L96-L97

We could add in a log message about an unsupported tag (probably at a debug / trace level). This should only be logged if the line isn't a comment, which we should be able to check for if the directive starts with '//'. There's been a semi-known bug where the current go.mod extraction doesn't handle comment lines very well. On the bright side, go.mod is rather opinionated about its formatting so we avoid a lot of interesting edge cases.
