### ISSUE TITLE
Setup nightly docker image builds

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#97]
Right now, there's no great way to quickly pull the images for main. The idea is to set up nightly builds that build, tag, and push the various docker images with a `nightly` tag. For the nightly tag, I think it's OK if we only provide it in amd64 at first.

The GitHub workflow should:
* Use a schedule to run the workflow every night
* Use a matrix build to do things in parallel
* Log into docker hub
* Run `make {component}/docker`, retag with `nightly`, and push to dockerhub

**Comment by mjpitz** [comment]
The primary challenge with this issue is going to be around testing, but there are many good examples within the repo to follow.

**Comment by jakeryang** [comment]
I'm interested in contributing to this.

Could you assign it to me?

**Comment by mjpitz** [comment]
@jakeryang assigned!
